# Discord bot token: see https://discord.com/developers/applications
token: 'YOUR_TOKEN_HERE'

tasks: 
#standart daily message is set to common example
    4: ["Common Example", "Another common example"]
    3: ["Frequent Example"]
    2: ["Infrequent Example"]
    1: ["Rare Example"]
# time to send a reminder message every 24 hours at 2pm
messageTime:
    hour: 14
    minutes : 0
# Do not send messages on Sunday
blacklistedDays: ['Sunday']
